name          'opentable-rundeck'
version       '0.1.0'
source        'git://github.com/opentable/puppet-rundeck.git'
author        'opentable'
summary       'Module for managing rundeck'
description   'Install and manage the configuration of the rundeck orchestration tool'
project_page  'https://github.com/opentable/puppet-rundeck'
license       'MIT'
dependency    'puppetlabs/stdlib'
