# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
require File.expand_path('../../../../puppetx/rundeck/acl', __FILE__)

# Validates the rundeck ACL policies
# Usage:
# Example:
# Parser
# ---- original file header ----
#
# @summary
#   
#
Puppet::Functions.create_function(:'rundeck::validate_rd_policy') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

  raise Puppet::ParseError, "validate_rd_policy(): wrong number of arguments (#{args.length}; must be 1)" unless args.length == 1

  args.each do |arg|
    next if arg.is_a?(Array)
    return PuppetX::Rundeck::ACL.validate_acl(arg) if arg.is_a?(Hash)
    raise Puppet::ParseError, "#{arg.inspect} is not a Hash or Array of hashes.  It looks to be a #{arg.class}"
  end

  end
end
