#!/bin/env bash

if [ -x /usr/bin/dpkg ]; then
  VERSION=`dpkg -l | grep rundeck | awk '{ print $3}'`
  echo "rundeck_version=$VERSION"
fi

if [ -x /usr/bin/yum ]; then
  VERSION=`yum list installed|awk '/rundeck\./{print $2}'`
  echo "rundeck_version=$VERSION"
fi
