#!/bin/bash

# dpkg-query will print "no packages found matching rundeck" on stderr if not installed, so
# all that needs to be done is redirect stderr
if $(command -v dpkg-query >/dev/null); then
    dpkg-query -W -f 'rundeck_version=${Version}\n' rundeck 2>/dev/null
fi

# rpm will produce "package rundeck is not installed" on stdout if not installed, so you must
# either silently check for existence or pipe the output to `grep -v`
if $(command -v rpm >/dev/null && rpm --quiet -q rundeck); then
    rpm -q --qf 'rundeck_version=%{VERSION}\n' rundeck
fi
